### ISSUE TITLE
Merge low abundance OTUs in an "Others" category

### ISSUE THREAD

**Issue by ericjcgalvez** [nosson/metagenomeSeq#17]
Dear Joseph,
Is there a way to merge low abundance OTUs in an "Others" category from a metagenomeSeq object?

have a AWESOME time

cheers

**Comment by nosson** [comment]
Hey Eric!

It was great to meet you the other day! Here is an example on how to merge low abundance OTUs. Alternatively you can aggregate to a level of the tree and throw those out that are below a threshold.

```r
source("http://bioconductor.org/biocLite.R")
biocLite("msd16s")
require(msd16s)

# Calculate which otu's are low abundance (threshold here was 75th quantile)
otuAbun = rowSums(msd16s)
lowAbunOtus = which(otuAbun<quantile(otuAbun,p=.75))

# Create annotation for low otus (warning), potentially
# consider removing low aggregated results instead?
otuNames = rownames(msd16s)
otuNames[lowAbunOtus] = "Other"

# Don't forget, you might want to normalize the data before aggregating. 
# See help for aggTax
aggResults = aggTax(msd16s,lvl=otuNames) 
```
Hope this helps, let me know if you have any other questions!
