### ISSUE TITLE
biom2MRexperiment error

### ISSUE THREAD

**Issue by ETaSky** [nosson/metagenomeSeq#22]
Dear Developers,
I have an error message popping out when I tried to convert a biom file produced from QIIME to MRexperiment object.
Here is the code, outputs and error messages I got:
library(biom)
> AF2=load_biom("otu_table.biom")
> AF2
MRexperiment (storageMode: environment)
assayData: 1406 features, 12 samples 
  element names: counts 
protocolData: none
phenoData: none
featureData
  featureNames: denovo0 denovo1 ... denovo1405 (1406 total)
  fvarLabels: taxonomy1 taxonomy2 ... taxonomy7 (7 total)
  fvarMetadata: labelDescription
experimentData: use 'experimentData(object)'
Annotation:  
> biom2MRexperiment(AF2)
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘biom_data’ for signature ‘"MRexperiment", "missing", "missing"’

Any ideas what went wrong? Is AF2 already a MRexperiment object after importing? Because I saw those info up there.
Thanks!

**Comment by nosson** [comment]
Hi @ETaSky,

Thanks for the interest. Yes, `load_biom` returns a MRexperiment object after importing. If you enter `?load_biom` you can see the help file that explains the output value (a MRexperiment object). I'll try to clean it up further if you think that'll help.

**Comment by ETaSky** [comment]
Thanks a lot! So you mean I do not need to do the biom2MRexperiment function as described in the manual, right?
The thing I found not right after using load_biom is that as you can see from previous thread, it lacked phenoData info. It does not have sampleNames. I do not know why is that.
I manually opened my biom file from QIIME 1.8.0 and found that although the file have all the info as the example files in the biom package, the two info "row" and "columns" come after "data". I am not sure if that caused the problem. 
Also, in the "columns" section which is supposedly to describe sample info, I found there is the "metadata" of each entry is NULL. I guess this is a QIIME issue. So I added the info by myself manually as the following:
"columns":[
{“id": "C3L", "metadata": {
“Treatment”:”Control”}},
{“id": "M3L", "metadata": {
“Treatment”:”Med”}},
{“id": "C2L", "metadata": {
“Treatment”:”Control”}},
{“id": "L3L", "metadata": {
“Treatment”:”Low”}},
{“id": "M2L", "metadata": {
“Treatment”:”Med”}},
{“id": "C1L", "metadata": {
“Treatment”:”Control”}},
{“id": "H3L", "metadata": {
“Treatment”:”High”}},
{“id": "L1L", "metadata": {
“Treatment”:”Low”}},
{“id": "L2L", "metadata": {
“Treatment”:”Low”}},
{“id": "M1L", "metadata": {
“Treatment”:”Med”}},
{“id": "H2L", "metadata": {
“Treatment”:”High”}},
{“id": "H1L", "metadata": {
“Treatment”:”High”}}
],
the original is { “id": "H1L", "metadata": NULL} etc.
After I saved the file as a biom file, I cannot load it into R with an error message:
Error in fromJSON(content, handler, default.size, depth, allowComments,  : 
  invalid JSON input
I guess the manually editing the biom file is not allowed?
So right now, I have no how I should proceed. 
Thanks!

**Comment by nosson** [comment]
@ETaSky Ah, I see. Yeah - I would recommend not trying to add the metadata information manually. If you have the information saved in a file like:
sample names along the top or rows: denovo0, ...,
metadata beneath each: high,low,etc.

You can read those in and assign them to the MRexperiment object based on the names. 

If you can send me a MRE (minimally reproducible example) of your biom file and metadata file I would be happy to get that into an MRexperiment object for you and a script showing you how.

**Comment by ETaSky** [comment]
@nosson Thank you very much! I'll try to work on it by myself first. I feel guilty for wasting your time. If I cannot solve the problem. I will then have to ask for your help. I'll let you know. Thanks again very much!

**Comment by ETaSky** [comment]
@nosson Just let you know, I used biom function in QIIME to add metadata into my otu table and then using load_biom () to load that file in R. Interestingly, now I have the phenoData info in my MRexperiment object.
So I have two questions regarding this. One is that my original otu table did have sample names. I could see their names in the "columns" field of my biom table. But not with any other metadata. So does the load_biom () ignore those info as long as they do not have metadata?
My other question is that in R biom package is a separate package other than metagenomeSeq. I was wondering why using load_biom in biom package could result in an MRexperiment object. Is that because I attached metagenomeSeq package at the beginning and then R would automatically treat related objects as MRexperiment objects? Also does that mean biom2MRexperiment function is not necessary any more?
Thanks a lot!

**Comment by nosson** [comment]
Answer 1: I'm sorry, I'm not sure I understand the question - can you send me a MRE? The function doesn't ignore any information. It relies on the biom package to load in the information.

Answer 2: The `load_biom` function is a wrapper around `biom` package's `read_biom` function to load a biom object into the R environment and then convert that biom object to a MRexperiment obj. 

Answer 3: The `biom2MRexperimen`t function is necessary if you have biom files laying around in your R session.
